---

# ansible-playbook -i hosts lesson-3-deploy-playbook.yml -e "ansible_user=frr ansible_ssh_pass=frr123 ansible_sudo_pass=frr123" -vv
      
- name: logging and motd
  hosts: localhost
  become: true
  tasks:
    - name: Copy motd file to frr and pc nodes
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 

    - name: labbing.log start message
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start FRR updates"
        create: yes
      delegate_to: localhost

- name: containerlab
  hosts: localhost
  become: true
  tasks:
    - name: add linux host bridge instances for pc connectivity to FRR topology
      command: "sudo util/add-bridges.sh"

    - name: deploy topology  
      command: "sudo containerlab deploy -t ../lesson-3-topo.yaml"
      ignore_errors: yes


    - name: labbing.log 
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: topology deployed"
        create: yes
      delegate_to: localhost

- name: Run frr base config playbook
  import_playbook: lesson-3-frr-base-playbook.yml
  ignore_errors: yes

