---

# ansible-playbook -i hosts lesson-3-deploy-playbook.yml -e "ansible_user=frr ansible_ssh_pass=frr123 ansible_sudo_pass=frr123" -vv
      
- name: start logging
  hosts: localhost
  become: true
  tasks:
    - name: labbing.log start message
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Starting containerlab deployment"
        create: yes
      delegate_to: localhost

- name: deploy topology
  hosts: localhost
  become: true
  tasks:
    - name: add linux host bridges for external connectivity to FRR topology
      command: "sudo util/add-bridges.sh"
      ignore_errors: yes

    - name: execute containerlab deploy   
      command: "containerlab deploy -t ../lesson-3-topo.yaml"
      ignore_errors: yes

    - name: labbing.log 
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: topology deployed, starting base config playbook"
        create: yes
      delegate_to: localhost

- name: Run frr base config playbook
  import_playbook: lesson-3-frr-base-playbook.yml
  ignore_errors: yes

