---

# ansible-playbook -i hosts lesson-3-destroy-playbook.yml -e "ansible_user=frr ansible_ssh_pass=frr123 ansible_sudo_pass=frr123" -vv
      
- name: destroy containerlab topology
  hosts: localhost
  become: true
  tasks:
    - name: destroy topology  
      command: "sudo containerlab destroy -t ../lesson-3-topo.yaml"
      ignore_errors: yes

    - name: labbing.log 
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: topology destroyed"
        create: yes
      delegate_to: localhost


