---

# ansible-playbook -i hosts lesson-3.2-deploy-playbook.yml -e "ansible_user=frr ansible_ssh_pass=frr123 ansible_sudo_pass=frr123" -vv
      
- name: logging
  hosts: localhost
  become: true
  tasks:

    - name: labbing.log start message
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Starting containerlab deployment"
        create: yes
      delegate_to: localhost

- name: deploy 3.2 topology
  hosts: localhost
  become: true
  tasks:

    - name: execute containerlab deploy   
      command: "sudo containerlab deploy -t ../lesson-3.2-topo.yaml"
      ignore_errors: yes


    - name: labbing.log 
      become: false
      lineinfile:
        path: "logs/labbing.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: topology deployed"
        create: yes
      delegate_to: localhost

- name: Run 3.2 base config playbook
  import_playbook: lesson-3.2-update-playbook.yml
  ignore_errors: yes

