---

# ansible-playbook -i hosts lesson-3-playbook.yml -e "ansible_user=frr ansible_ssh_pass=frr123 ansible_sudo_pass=frr123" -vv
      
- name: motd
  hosts: frr
  become: true
  tasks:
    - name: Copy motd file to frr and pc nodes
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 

- name: Start logging to local deploy.log file
  hosts: localhost
  become: false
  tasks:
      
    - name: deploy.log start message
      become: false
      lineinfile:
        path: "logs/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start FRR updates"
        create: yes
      delegate_to: localhost
      
- name: Update FRR configurations
  hosts: frr
  become: true
  tasks: 
      
    - name: Create a backup of the existing FRR daemons file
      command: cp /etc/frr/daemons /etc/frr/daemons.bak
      args:
        creates: /etc/frr/daemons.bak
      ignore_errors: yes
      register: backup_result

    - name: stop frr
      command: "sudo /usr/lib/frr/frr stop"
      ignore_errors: yes

    - name: Upload new frr daemons file with bfdd enabled
      copy:
        src: "{{ inventory_hostname }}/daemons"
        dest: "/etc/frr/daemons"
        mode: 0644

    - name: restart frr
      command: "sudo /usr/lib/frr/frr start"
      ignore_errors: yes

    - name: deploy.log daemons status
      become: false
      lineinfile:
        path: "logs/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: daemons file updated"
        create: yes
      delegate_to: localhost

    # - name: pause for 15 seconds while frr restarts
    #   pause:
    #     seconds: 15
    #   become: false



