---
- name: FRR BGP
  hosts: frr
  become: false
  tasks:
  - name: configure global bgp as 65000
    hosts: frr-1
    frr.frr.frr_bgp:
      config:
        bgp_as: 65000
        router_id: 10.0.0.1
        log_neighbor_changes: True
        neighbors:
          - neighbor: 10.0.0.4
            remote_as: 65000
            timers:
              keepalive: 120
              holdtime: 360
          - neighbor: 10.0.0.5
            remote_as: 65000
        networks:
          - prefix: 10.0.0.1
            masklen: 32
          - prefix: 10.1.3.0/24
            masklen: 24
        address_family:
          - afi: ipv4
            safi: unicast
      operation: merge