# roles/frr_bgp/tasks/main.yml
---
- name: Configure BGP Router ID
  ansible.builtin.command: vtysh -c "configure terminal" -c "router bgp {{ bgp.as }}" -c "bgp router-id {{ bgp.router_id }}"

- name: Configure BGP Networks
  ansible.builtin.command: vtysh -c "configure terminal" -c "router bgp {{ bgp.as }}" -c "network {{ item.prefix }}"
  with_items: "{{ bgp.networks }}"

- name: Configure BGP Neighbors
  ansible.builtin.command: vtysh -c "configure terminal" -c "router bgp {{ bgp.as }}" -c "neighbor {{ item.address }} remote-as {{ item.remote_as }}"
  with_items: "{{ bgp.neighbors }}"
